# Process/action scope
WITH_NORMALIZATION_NO_CMD="Normalization command must have an inner command.\n\tIn proof.......: {0}"

USE_CMD_THMNAME="Incompatible type for theorem reference in use command.\n\tIn proof.......: {0}\n\tTheorem........: {1}\n\tType expected..: proof type\n\tType found.....: {2}"
USE_CMD_REPL="Incompatible type in variable replacement of use command.\n\tIn proof.......: {0}\n\tAt position....: {1} (of {2})\n\tVariable name..: {3}\n\tType expected..: {4}\n\tType found.....: {5}."
USE_CMD_INVALID_REPL="Invalid instantiation kind for replacement in use command.\n\tIn proof.......: {0}\n\tAt position....: {1} (of {2})\n\tVariable name..: {3}."

SUBST_CMD_PRED_INVOKE="Undeclared name in invoke command.\n\tIn proof....: {0}\n\tName........: {1}\n\tType found..: {2}"
SUBST_CMD_BADNAME_INVOKE="Invoke command can have at most one reference name.\n\tIn proof.....: {0}\n\tNames found..: {1}"

QNT_CMD_INVALID_INST="Invalid instantiation kind in instantiate command.\n\tIn proof.......: {0}\n\tAt position....: {1} (of {2})\n\tVariable name..: {3}."
QNT_CMD_INST="Incompatible type in variable instantiation of instantiate command.\n\tIn proof.......: {0}\n\tAt position....: {1} (of {2})\n\tVariable name..: {3}\n\tType expected..: {4}\n\tType found.....: {5}."

APPLY_CMD_THMNAME="Incompatible type for theorem name in apply command.\n\tIn proof.......: {0}\n\tTheorem........: {1}\n\tType expected..: proof type\n\tType found.....: {2}"

WITH_CMD_INVALID="No inner command for with command.\n\tIn proof.......: {0}"
WITH_CMD_THMNAME="Incompatible type for theorem reference in with command.\n\tIn proof.......: {0}\n\tTheorem........: {1}\n\tType expected..: proof type\n\tType found.....: {2}"

UNEXPECTED_EXCEPTION_ERROR=An unexpected exception has occurred. This can only be a bug, and should not happen.\nPlease report it to ''czt-devel@lists.sourceforge.net''. \n\tSummary.....: {0}\n\tException...: {1}\n\tStack trace.: {2}
